spring.config.import=application-common.properties,application-jpa.properties,application-jackson.properties,application-mvc.properties
#spring.profiles.include=common,jpa,jackson,mvc
server.port=8080
spring.application.name=XManager
server.servlet.context-path=/Manager
#设置SpringBoot运行模式为SERVLET模式：阻塞同步Web模式
spring.main.web-application-type=servlet
spring.banner.location=classpath:/banner/banner-manager.txt
#ServerManager默认的slf4j配置文件
logging.config=${xworx.home}/codebase/config/logback/logback-manager.xml
com.xworx.cmd.executor=cmd.exe /C start
com.xworx.java.cmd="${java.home}"/bin/java -Dxworx.home=${xworx.home}
com.xworx.Zookeeper.enabled=true
com.xworx.Zookeeper.embedded=true
com.xworx.IgniteServer.enabled=false
com.xworx.MethodServer.enabled=true
com.xworx.MethodServer.count=0
com.xworx.MinioServer.enabled=true
com.xworx.ServerManager.java.heap=-Xms512m -Xmx512m
com.xworx.ServerManager.java.agent=
com.xworx.ServerManager.java.args=${com.xworx.java.cmd} ${com.xworx.ServerManager.java.agent} -server ${com.xworx.ServerManager.java.heap} -Dfile.encoding=UTF-8
com.xworx.ServerManager.main.args=--spring.profiles.active=manager
com.xworx.ServerManager.classpath.args="${xworx.home}/codebase;${xworx.home}/lib/*;${xworx.home}/zookeeper/lib/*;${xworx.home}/zookeeper/conf"
com.xworx.ServerManager.launcher.command=${com.xworx.cmd.executor} "XManager" ${com.xworx.ServerManager.java.args} ${com.xworx.Zookeeper.logs.args} -cp ${com.xworx.ServerManager.classpath.args} com.xworx.XWorxManagerApplication ${com.xworx.ServerManager.main.args}
com.xworx.MinioServer.main.args=--address ":${minio.api.port}" --console-address ":${minio.web.port}" ${xworx.home}/storage/vaults
com.xworx.MinioServer.launcher.command=${com.xworx.cmd.executor} "Minio" ${xworx.home}/bin/minio.exe server ${com.xworx.MinioServer.main.args}
com.xworx.MinioServer.timeout=5000
com.xworx.Zookeeper.java.heap=-Xms512m -Xmx512m
com.xworx.Zookeeper.java.opens=
com.xworx.Zookeeper.java.exports=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
com.xworx.Zookeeper.java.agent=-javaagent:${xworx.home}/codebase/xagent.jar
com.xworx.Zookeeper.java.args=${com.xworx.java.cmd} ${com.xworx.Zookeeper.java.agent} -server ${com.xworx.Zookeeper.java.heap} ${com.xworx.Zookeeper.java.exports} ${com.xworx.Zookeeper.java.opens} "-XX:+HeapDumpOnOutOfMemoryError" "-XX:OnOutOfMemoryError=cmd /c taskkill /pid %%p /t /f"
#AdminServer默认就是启用的，而且接受来自任何IP的请求，为了安全可以禁用 -Dzookeeper.admin.enableServer=false
com.xworx.Zookeeper.logs.args="-Dzookeeper.log.dir=${xworx.home}/storage/zookeeper/logs" "-Dzookeeper.root.logger=INFO,CONSOLE" -Dzookeeper.admin.enableServer=false
com.xworx.Zookeeper.classpath.args="${xworx.home}/codebase;${xworx.home}/lib/*;${xworx.home}/zookeeper/lib/*;${xworx.home}/zookeeper/conf"
com.xworx.Zookeeper.main.args=--spring.profiles.active=zookeeper
com.xworx.Zookeeper.launcher.command=${com.xworx.cmd.executor} "ZooKeeper" ${com.xworx.Zookeeper.java.args} ${com.xworx.Zookeeper.logs.args} -cp ${com.xworx.Zookeeper.classpath.args} com.xworx.boot.ZookeeperLauncherMain ${com.xworx.Zookeeper.main.args}
com.xworx.Zookeeper.timeout=15000
com.xworx.IgniteServer.java.heap=-Xms1024m -Xmx1024m
com.xworx.IgniteServer.java.opens=--add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED
com.xworx.IgniteServer.java.exports=--add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=java.management/com.sun.jmx.mbeanserver=ALL-UNNAMED --add-exports=jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED --add-exports=java.base/sun.reflect.generics.reflectiveObjects=ALL-UNNAMED
com.xworx.IgniteServer.java.agent=-javaagent:${xworx.home}/codebase/xagent.jar
com.xworx.IgniteServer.ignite.home=-DIGNITE_HOME="${xworx.home}/storage/ignite"
com.xworx.IgniteServer.java.args=${com.xworx.java.cmd} ${com.xworx.IgniteServer.java.agent} -server ${com.xworx.IgniteServer.java.heap} ${com.xworx.IgniteServer.java.exports} ${com.xworx.IgniteServer.java.opens} ${com.xworx.IgniteServer.ignite.home} -Dfile.encoding=UTF-8
com.xworx.IgniteServer.classpath.args="${xworx.home}/codebase;${xworx.home}/lib/*;${xworx.home}/ignite/libs/*;${xworx.home}/ignite/libs/ignite-indexing/*;${xworx.home}/ignite/libs/ignite-spring/*;${xworx.home}/ignite/libs/ignite-zookeeper/*"
com.xworx.IgniteServer.main.args=--spring.profiles.active=ignite
com.xworx.IgniteServer.launcher.command=${com.xworx.cmd.executor} "IgniteServer" ${com.xworx.IgniteServer.java.args} -cp ${com.xworx.IgniteServer.classpath.args} com.xworx.boot.XWorxIgniteLauncherMain ${com.xworx.IgniteServer.main.args}
com.xworx.IgniteServer.timeout=15000
com.xworx.MethodServer.java.heap=-Xms512m -Xmx512m
com.xworx.MethodServer.java.opens=-Djava.security.egd=file:/dev/./urandom
com.xworx.MethodServer.java.exports=--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
com.xworx.MethodServer.java.agent=-javaagent:${xworx.home}/codebase/xagent.jar
com.xworx.MethodServer.java.args=${com.xworx.java.cmd} ${com.xworx.MethodServer.java.agent} -server ${com.xworx.MethodServer.java.heap} ${com.xworx.MethodServer.java.exports} ${com.xworx.MethodServer.java.opens} "-XX:+HeapDumpOnOutOfMemoryError" "-XX:+EnableDynamicAgentLoading" "-XX:OnOutOfMemoryError=cmd /c taskkill /pid %%p /t /f"
com.xworx.MethodServer.classpath.args="${xworx.home}/codebase;${xworx.home}/lib/*"
com.xworx.MethodServer.timeout=20000
com.xworx.MethodServer.java.args.1=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8081 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8001
com.xworx.MethodServer.main.args.1=--spring.profiles.active=method --server.port=8081 --ajp.port=8011 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.1=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.1} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.1}
com.xworx.MethodServer.java.args.2=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8082 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8002
com.xworx.MethodServer.main.args.2=--spring.profiles.active=method --server.port=8082 --ajp.port=8012 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.2=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.2} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.2}
com.xworx.MethodServer.java.args.3=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8083
com.xworx.MethodServer.main.args.3=--spring.profiles.active=method --server.port=8083 --ajp.port=8013 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.3=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.3} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.3}
com.xworx.MethodServer.java.args.4=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8084
com.xworx.MethodServer.main.args.4=--spring.profiles.active=method --server.port=8084 --ajp.port=8014 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.4=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.4} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.4}
com.xworx.MethodServer.java.args.5=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8085
com.xworx.MethodServer.main.args.5=--spring.profiles.active=method --server.port=8085 --ajp.port=8015 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.5=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.5} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.5}
com.xworx.MethodServer.java.args.6=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8086
com.xworx.MethodServer.main.args.6=--spring.profiles.active=method --server.port=8086 --ajp.port=8016 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.6=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.6} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.6}
com.xworx.MethodServer.java.args.7=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8087
com.xworx.MethodServer.main.args.7=--spring.profiles.active=method --server.port=8087 --ajp.port=8017 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.7=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.7} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.7}
com.xworx.MethodServer.java.args.8=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8088
com.xworx.MethodServer.main.args.8=--spring.profiles.active=method --server.port=8088 --ajp.port=8018 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.8=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.8} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.8}
com.xworx.MethodServer.java.args.9=-DTHINGWORX_PLATFORM_SETTINGS=${xworx.home}/codebase/config/thingworx -DHTTP_PORT=8089
com.xworx.MethodServer.main.args.9=--spring.profiles.active=method --server.port=8089 --ajp.port=8019 --thingworx.enabled=false
com.xworx.MethodServer.launcher.command.9=${com.xworx.cmd.executor} "XMethod" ${com.xworx.MethodServer.java.args} ${com.xworx.MethodServer.java.args.9} -cp ${com.xworx.MethodServer.classpath.args} com.xworx.boot.XWorxMethodLauncherMain ${com.xworx.MethodServer.main.args.9}
#web-console arthas-tunnel-server 支持wss
arthas.server.ssl=false
arthas.enable-detail-pages=true
#配置arthas.server.ssl=true，arthas.tunnel-server就必须设置wss
arthas.tunnel-server=ws://${arthas.server.host}:${arthas.server.port}/ws
#客户端id,应用名@随机值，tunnel server会截取分隔符@前面的字符串作为应用名: ServerManager@8080
arthas.agent-id=${spring.application.name}@${server.port}
