#关闭定时任务Job
flowable.async-executor-activate=false
#自动更新数据库
flowable.database-schema-update=true
#创建Flowable数据库历史记录表
flowable.db-history-used=true
#Flowable记录历史任务数据级别，full:记录最全
flowable.history-level=full
#启动的时候,是否检查文件目录对应的流程文件
flowable.check-process-definitions=true
#Flowable启动时会自动部署下面位置中的xflow
flowable.process-definition-location-prefix=classpath:/templates/xflow/
flowable.process-definition-location-suffixes=**.bpmn
#进入IDM身份管理引擎
flowable.idm.enabled=false
flowable.cmmn.enabled=false
flowable.app.enabled=false
