# 设置RestController返回json的时间格式
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8
spring.jackson.serialization.indent-output=true
# 不对null进行序列化
spring.jackson.default-property-inclusion=NON_NULL
# 允许jackson忽略对象中不存在的属性
spring.jackson.deserialization.fail_on_unknown_properties=false
# 允许出现特殊字符和转义字符
spring.jackson.parser.allow_unquoted_control_chars=true
# 允许出现单引号
spring.jackson.parser.allow_single_quotes=true
