# 修改默认的静态寻址资源目录,多个使用逗号分隔
spring.resources.static-locations=classpath:/
# 是否启用freemarker
spring.freemarker.enabled=true
# 配置FreeMarker模板文件的位置
spring.freemarker.template-loader-path=classpath:/
# 设置模板后缀名，在url引用时就不需要写ftl后缀了，不然freemarker不会去解析内容
spring.freemarker.suffix=.ftl
spring.freemarker.view-names=freemarker/*,/freemarker/*,XWorx/freemarker/*,/XWorx/freemarker/*
# 设置Content-Type的值
spring.freemarker.content-type=text/html
# 设置页面编码格式
spring.freemarker.charset=UTF-8
# 设置页面缓存, 开发阶段最好设置为false
spring.freemarker.cache=false
# 是否将HttpServletRequest中的属性添加到Model中
spring.freemarker.expose-request-attributes=false
# 是否将HttpSession中的属性添加到Model中
spring.freemarker.expose-session-attributes=false
# 检查模板位置是否存在
spring.freemarker.check-template-location=true
# 是否优先从文件系统中加载template，以支持热加载，默认为true
spring.freemarker.prefer-file-system-access=true
# 是否在freemarker中使用request.contextPath
spring.freemarker.request-context-attribute=true
# 为XWorx配置Thymeleaf
spring.thymeleaf.prefix=classpath:/
spring.thymeleaf.view-names=thymeleaf/*,/thymeleaf/*,XWorx/thymeleaf/*,/XWorx/thymeleaf/*
spring.thymeleaf.check-template-location=true
spring.thymeleaf.content-type=text/html
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
# 设置页面缓存, 开发阶段最好设置为false
spring.thymeleaf.cache=false

# 文件上传大小限制
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mvc.view.prefix=/jsp/
spring.mvc.view.suffix=.jsp
